#!/usr/bin/env python3
"""Emit governance-scorecard and reliability-synthesis LaTeX tables + summary counts.
Reproducible: run from cfo-agents-survey/ root. 2026-07-16. Sources: matrix/*.csv (coded from corpus/notes/)."""
import csv, os
os.chdir(os.path.dirname(os.path.abspath(__file__)) + '/..')
G = {'Y':r'\CIRCLE','P':r'\LEFTcircle','N':r'$\cdot$'}

# ---- governance scorecard ----
rows = list(csv.DictReader(open('matrix/governance_scorecard.csv')))
def g(v): return G.get(v.strip(),'')
# caption tallies derived from the same CSV so printed counts are mechanically checkable
def yc(d): return sum(1 for r in rows if r[d].strip()=='Y')
def pc(d): return sum(1 for r in rows if r[d].strip()=='P')
NONE = sum(1 for r in rows if all(r[d].strip()=='N' for d in ['PROV','SOD','TIE','REP']))
CAPCOUNTS = (r'Column tallies (\CIRCLE/\LEFTcircle): provenance %d/%d, SoD %d/%d, tie-out %d/%d, '
             r'repetition %d/%d; %d rows measure none.}'
             % (yc('PROV'),pc('PROV'),yc('SOD'),pc('SOD'),yc('TIE'),pc('TIE'),yc('REP'),pc('REP'),NONE))
half=(len(rows)+1)//2
A,B=rows[:half],rows[half:]
def cells(r): return f"{r['bibkey'].replace('_',chr(92)+'_')} & {g(r['PROV'])} & {g(r['SOD'])} & {g(r['TIE'])} & {g(r['REP'])}"
L=[r'% Auto-generated by matrix/build_extra_tables.py from governance_scorecard.csv',
   r'\begin{table*}[tp]\centering\scriptsize\setlength{\tabcolsep}{3pt}\renewcommand{\arraystretch}{0.9}',
   r'\begin{tabular}{@{}lcccc@{\hspace{2em}}lcccc@{}}\toprule',
   r'Benchmark & Pr. & SoD & Tie & Rep.$^k$ & Benchmark & Pr. & SoD & Tie & Rep.$^k$ \\ \midrule']
for i in range(half):
    left=cells(A[i]); right=cells(B[i]) if i<len(B) else ' & & & & '
    L.append(left+' & '+right+' \\\\')
L += [r'\bottomrule\end{tabular}',
 r'\caption{Governance scorecard: which of the 32 scored benchmarks/systems \emph{measure} the four control dimensions of \S\ref{sec:governance} '
 r'(\CIRCLE{}=measured, \LEFTcircle{}=partial/indirect, $\cdot$=not measured). Same row set as Table~\ref{tab:coverage} and its appendix continuation. '
 r"Rep.$^k$ is pass$^k$ under identical re-runs, narrower than the broader degradation of Table~\ref{tab:reliability}. Coded from each paper's reported design; justifications released. "
 + CAPCOUNTS,
 r'\label{tab:governance}\end{table*}']
open('paper/figures/governance_table.tex','w').write('\n'.join(L)+'\n')

# summary counts (only Y counts as "measures")
core = [r for r in rows if r['band']=='core']
def cnt(dim,val='Y',rs=rows): return sum(1 for r in rs if r[dim].strip()==val)
print("=== GOVERNANCE (all", len(rows), "rows;", len(core), "core) ===")
for d in ['PROV','SOD','TIE','REP']:
    print(f"  {d}: Y={cnt(d)} (core Y={cnt(d,'Y',core)}), partial={cnt(d,'P')}")
anyY = sum(1 for r in rows if any(r[d].strip()=='Y' for d in ['PROV','SOD','TIE','REP']))
noneG = sum(1 for r in rows if all(r[d].strip()=='N' for d in ['PROV','SOD','TIE','REP']))
print(f"  >=1 dim measured (Y): {anyY}/{len(rows)}; ZERO governance dim: {noneG}/{len(rows)}")

# ---- reliability synthesis ----
rr = list(csv.DictReader(open('matrix/reliability_synthesis.csv')))
L2 = [r'% Auto-generated by matrix/build_extra_tables.py from reliability_synthesis.csv',
     r"\begin{table*}[t]\centering\footnotesize\setlength{\tabcolsep}{6pt}",
     r'\begin{tabular}{@{}lllll@{}}\toprule',
     r'Benchmark & Single-step & Composed & $\Delta$ & Construct \\ \midrule']
for r in rr:
    bk = r['bibkey'].replace('finmaster2025b','finmaster2025').replace('_',chr(92)+'_')
    L2.append(f"{bk} & {r['basic']} & {r['composed']} & {r['delta']} & {r['construct']} \\\\")
L2 += [r'\bottomrule\end{tabular}',
 r'\caption{Reliability degradation across the corpus. Every benchmark that reports a basic/single-step number \emph{and} a composed, '
 r'multi-step, or repeated number shows the composed value is worse. The constructs differ (repetition, composition, self-report-vs-replay, '
 r'horizon); the pattern of degradation under composition does not. We report them together as a pattern, not a single commensurable metric.}',
 r'\label{tab:reliability}\end{table*}']
open('paper/figures/reliability_table.tex','w').write('\n'.join(L2)+'\n')
print("\n=== RELIABILITY: %d benchmark rows, all show degradation ===" % len(rr))
print("tables written: paper/figures/governance_table.tex, reliability_table.tex")
